# Generated by Django 3.0 on 2024-05-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors_books", "0001_add_authors_and_books"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("name", "author"), ("name", "description")},
        ),
    ]
