# Generated by Django 3.0 on 2024-05-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors_books", "0002_add_unique_constraint_for_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
    ]
